<?php

return [
    'initial_cash' => 8_000_000,
    'start_bonus' => 2_000_000,
    'max_players' => 8,
    'max_rounds' => 30,
    'max_houses_per_property' => 5,
    'max_houses_per_build_action' => 2,
    'jail_position' => 10,
    'board' => [
        ['index' => 0, 'type' => 'start', 'name' => '起点', 'icon' => '🏁'],
        ['index' => 1, 'type' => 'city', 'name' => '罗马', 'price' => 200_000, 'rent' => 40_000, 'house_price' => 500_000, 'color' => '#d64f45'],
        ['index' => 2, 'type' => 'chance', 'name' => '机会', 'icon' => '？'],
        ['index' => 3, 'type' => 'city', 'name' => '雅典', 'price' => 400_000, 'rent' => 80_000, 'house_price' => 500_000, 'color' => '#d64f45'],
        ['index' => 4, 'type' => 'rail', 'name' => '中央铁路', 'price' => 220_000, 'rent' => 35_000, 'icon' => '🚆'],
        ['index' => 5, 'type' => 'city', 'name' => '巴黎', 'price' => 600_000, 'rent' => 120_000, 'house_price' => 500_000, 'color' => '#e0a83a'],
        ['index' => 6, 'type' => 'welfare', 'name' => '公益福利', 'icon' => '❤'],
        ['index' => 7, 'type' => 'city', 'name' => '伦敦', 'price' => 800_000, 'rent' => 160_000, 'house_price' => 500_000, 'color' => '#e0a83a'],
        ['index' => 8, 'type' => 'air', 'name' => '国际航空', 'price' => 300_000, 'rent' => 45_000, 'icon' => '✈'],
        ['index' => 9, 'type' => 'city', 'name' => '纽约', 'price' => 1_000_000, 'rent' => 200_000, 'house_price' => 500_000, 'color' => '#4f7bd9'],
        ['index' => 10, 'type' => 'jail', 'name' => '监狱', 'icon' => '🔒'],
        ['index' => 11, 'type' => 'city', 'name' => '东京', 'price' => 1_200_000, 'rent' => 240_000, 'house_price' => 500_000, 'color' => '#4f7bd9'],
        ['index' => 12, 'type' => 'chance', 'name' => '机会', 'icon' => '？'],
        ['index' => 13, 'type' => 'city', 'name' => '首尔', 'price' => 1_400_000, 'rent' => 280_000, 'house_price' => 500_000, 'color' => '#5aa469'],
        ['index' => 14, 'type' => 'rail', 'name' => '海岸铁路', 'price' => 220_000, 'rent' => 35_000, 'icon' => '🚆'],
        ['index' => 15, 'type' => 'city', 'name' => '新加坡', 'price' => 1_600_000, 'rent' => 320_000, 'house_price' => 500_000, 'color' => '#5aa469'],
        ['index' => 16, 'type' => 'welfare', 'name' => '公益福利', 'icon' => '❤'],
        ['index' => 17, 'type' => 'city', 'name' => '迪拜', 'price' => 1_800_000, 'rent' => 360_000, 'house_price' => 500_000, 'color' => '#a45fb4'],
        ['index' => 18, 'type' => 'air', 'name' => '洲际航空', 'price' => 300_000, 'rent' => 45_000, 'icon' => '✈'],
        ['index' => 19, 'type' => 'city', 'name' => '悉尼', 'price' => 2_000_000, 'rent' => 400_000, 'house_price' => 500_000, 'color' => '#a45fb4'],
        ['index' => 20, 'type' => 'chance', 'name' => '机会', 'icon' => '？'],
        ['index' => 21, 'type' => 'city', 'name' => '柏林', 'price' => 2_200_000, 'rent' => 440_000, 'house_price' => 500_000, 'color' => '#14b8a6'],
        ['index' => 22, 'type' => 'rail', 'name' => '山脊铁路', 'price' => 260_000, 'rent' => 42_000, 'icon' => '🚆'],
        ['index' => 23, 'type' => 'city', 'name' => '马德里', 'price' => 2_400_000, 'rent' => 480_000, 'house_price' => 500_000, 'color' => '#14b8a6'],
        ['index' => 24, 'type' => 'welfare', 'name' => '公益福利', 'icon' => '❤'],
        ['index' => 25, 'type' => 'city', 'name' => '开罗', 'price' => 2_600_000, 'rent' => 520_000, 'house_price' => 500_000, 'color' => '#f97316'],
        ['index' => 26, 'type' => 'air', 'name' => '天空航空', 'price' => 340_000, 'rent' => 52_000, 'icon' => '✈'],
        ['index' => 27, 'type' => 'city', 'name' => '洛杉矶', 'price' => 2_800_000, 'rent' => 560_000, 'house_price' => 500_000, 'color' => '#f97316'],
    ],
    'chance_cards' => [
        ['code' => 'bonus', 'title' => '项目分红', 'description' => '获得 300K', 'action' => 'cash', 'amount' => 300_000],
        ['code' => 'tax', 'title' => '临时税单', 'description' => '支付 180K', 'action' => 'cash', 'amount' => -180_000],
        ['code' => 'angel_investment', 'title' => '天使投资', 'description' => '获得 800K', 'action' => 'cash', 'amount' => 800_000],
        ['code' => 'market_swing', 'title' => '市场波动', 'description' => '支付 350K', 'action' => 'cash', 'amount' => -350_000],
        ['code' => 'city_award', 'title' => '城市评选获奖', 'description' => '获得 500K', 'action' => 'cash', 'amount' => 500_000],
        ['code' => 'go_start', 'title' => '快速通道', 'description' => '前往起点并领取奖励', 'action' => 'move_to', 'position' => 0, 'grant_start_bonus' => true],
        ['code' => 'go_jail', 'title' => '违规施工', 'description' => '进入监狱', 'action' => 'jail'],
        ['code' => 'move_forward', 'title' => '顺风车', 'description' => '前进 3 格', 'action' => 'move_steps', 'steps' => 3],
        ['code' => 'move_forward_two', 'title' => '贵宾通道', 'description' => '前进 2 格', 'action' => 'move_steps', 'steps' => 2],
        ['code' => 'move_forward_five', 'title' => '专车接送', 'description' => '前进 5 格', 'action' => 'move_steps', 'steps' => 5],
        ['code' => 'visit_tokyo', 'title' => '商务航线', 'description' => '前往东京', 'action' => 'move_to', 'position' => 11, 'grant_start_bonus' => false],
        ['code' => 'visit_singapore', 'title' => '国际会议', 'description' => '前往新加坡', 'action' => 'move_to', 'position' => 15, 'grant_start_bonus' => false],
    ],
    'welfare_cards' => [
        ['code' => 'community_bonus', 'title' => '公益基金', 'description' => '获得 220K', 'action' => 'cash', 'amount' => 220_000],
        ['code' => 'repair', 'title' => '城市维护', 'description' => '支付 80K', 'action' => 'cash', 'amount' => -80_000],
        ['code' => 'education_grant', 'title' => '教育补助', 'description' => '获得 400K', 'action' => 'cash', 'amount' => 400_000],
        ['code' => 'medical_support', 'title' => '医疗援助', 'description' => '获得 300K', 'action' => 'cash', 'amount' => 300_000],
        ['code' => 'charity_donation', 'title' => '公益捐款', 'description' => '支付 200K', 'action' => 'cash', 'amount' => -200_000],
        ['code' => 'jail_free', 'title' => '法律援助', 'description' => '获得出狱卡', 'action' => 'jail_card'],
        ['code' => 'go_start', 'title' => '志愿者专车', 'description' => '回到起点并领取奖励', 'action' => 'move_to', 'position' => 0, 'grant_start_bonus' => true],
        ['code' => 'volunteer_trip', 'title' => '志愿服务', 'description' => '前进 4 格', 'action' => 'move_steps', 'steps' => 4],
        ['code' => 'community_visit', 'title' => '社区走访', 'description' => '前往巴黎', 'action' => 'move_to', 'position' => 5, 'grant_start_bonus' => false],
        ['code' => 'legal_delay', 'title' => '纠纷调解', 'description' => '进入监狱', 'action' => 'jail'],
    ],
];
